- hosts: rpmservers
  become: true
  tasks:
    - name: Copy RPM package
      copy:
        src: ./hello_world-2.0-1.noarch.rpm
        dest: /tmp/hello_world.rpm

    - name: Install hello_world RPM with zypper
      zypper:
        name: /tmp/hello_world.rpm
        state: present

    - name: Run hello_world command
      command: /usr/local/bin/hello_world
      register: hello_output

    - name: Show stdout
      debug:
        var: hello_output.stdout

    - name: Show stderr
      debug:
        var: hello_output.stderr
